version: "3.9"
services:
    gateway-server:
        build: ../gateway-server/
        image: martinsgms/ra-gateway-server:v0.1
        container_name: ra-gateway-server
        ports:
            - "5555:5555"