CREATE TABLE TRA_USUARIO (
    ID BIGINT,
    TE_EMAIL VARCHAR(100),
    NM_NOME VARCHAR(100)
);

ALTER TABLE TRA_USUARIO ADD constraint PK_TRA_PACIENTE PRIMARY KEY (ID) ;
ALTER TABLE TRA_USUARIO modify ID BIGINT auto_increment;

---------- GENERATED:

Hibernate: 
    
    create table tvamr_evento (
       id bigint generated by default as identity,
        dh_evento timestamp,
        ds_evento varchar(255),
        nu_pa_diastolica integer,
        nu_pa_sistolica integer,
        ds_sintoma varchar(255),
        id_exame bigint,
        primary key (id)
    )
Hibernate: 
    
    create table tvamr_exame (
       id bigint generated by default as identity,
        dh_exame timestamp,
        id_externo varchar(255),
        nu_intervalo_afericao integer,
        id_paciente bigint,
        id_servico_saude bigint,
        cd_status varchar(255),
        primary key (id)
    )
Hibernate: 
    
    create table tvamr_paciente (
       id bigint generated by default as identity,
        te_email varchar(255),
        nm_nome varchar(255),
        primary key (id)
    )
Hibernate: 
    
    create table tvamr_servico_saude (
       id bigint generated by default as identity,
        nm_bairro varchar(255),
        te_cep varchar(255),
        nm_cidade varchar(255),
        nu_cnpj varchar(255),
        nm_estado varchar(255),
        nu_latitude bigint,
        nm_logradouro varchar(255),
        nu_longitude bigint,
        nu_numero_lote bigint,
        nm_completo varchar(255),
        nm_curto varchar(255),
        primary key (id)
    )
Hibernate: 
    
    create table tvamr_status_exame (
       cd_status varchar(255) not null,
        ds_descricao varchar(255),
        in_permite_escrita boolean,
        primary key (cd_status)
    )
Hibernate: 
    
    alter table tvamr_evento 
       add constraint FKevwbv5eqx14cq58pwo4c5fx8l 
       foreign key (id_exame) 
       references tvamr_exame
Hibernate: 
    
    alter table tvamr_exame 
       add constraint FK1fj63k5klewdt9imo5uevtchy 
       foreign key (id_paciente) 
       references tvamr_paciente
Hibernate: 
    
    alter table tvamr_exame 
       add constraint FK4bg7b7omwxi6tvcfohovul3u7 
       foreign key (id_servico_saude) 
       references tvamr_servico_saude
Hibernate: 
    
    alter table tvamr_exame 
       add constraint FKttk7swr31m434u6r7vj5jkt2 
       foreign key (cd_status) 
       references tvamr_status_exame