----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------
-- DDL FOR: TRA_USUARIO
----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE TRA_USUARIO (
    ID BIGINT,
    TE_EMAIL VARCHAR(100),
    NM_NOME VARCHAR(100)
);

ALTER TABLE TRA_USUARIO ADD CONSTRAINT PK_TRA_PACIENTE PRIMARY KEY (ID);
ALTER TABLE TRA_USUARIO MODIFY ID BIGINT AUTO_INCREMENT;

----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------
-- DDL FOR: TRA_EVENTO
----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE TRA_EVENTO (
    ID BIGINT,
    DH_EVENTO TIMESTAMP,
    DS_EVENTO VARCHAR(100),
    NU_PA_DIASTOLICA INTEGER,
    NU_PA_SISTOLICA INTEGER,
    DS_SINTOMA VARCHAR(100),
    ID_EXAME BIGINT
);

ALTER TABLE TRA_EVENTO ADD CONSTRAINT PK_TRA_EVENTO PRIMARY KEY (ID);
ALTER TABLE TRA_EVENTO MODIFY ID BIGINT AUTO_INCREMENT;

ALTER TABLE TRA_EVENTO 
ADD CONSTRAINT FK_TRA_EVENTO_EXAME 
FOREIGN KEY (ID_EXAME) 
REFERENCES TRA_EXAME (ID); 

----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------
-- DDL FOR: TRA_EXAME
----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE TRA_EXAME (
    ID BIGINT,
    DH_EXAME TIMESTAMP,
    ID_EXTERNO VARCHAR(100),
    NU_INTERVALO_AFERICAO INTEGER,
    ID_PACIENTE BIGINT,
    ID_SERVICO_SAUDE BIGINT,
    CD_STATUS VARCHAR(100)
);

ALTER TABLE TRA_EXAME ADD CONSTRAINT PK_TRA_EXAME PRIMARY KEY (ID);
ALTER TABLE TRA_EXAME MODIFY ID BIGINT AUTO_INCREMENT;

ALTER TABLE TRA_EXAME 
ADD CONSTRAINT FK_TRA_EXAME_ID_USUARIO
FOREIGN KEY (ID_USUARIO) 
REFERENCES TRA_USUARIO (ID);

----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------
-- DDL FOR: TRA_STATUS_EXAME
----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE TRA_STATUS_EXAME (
    CD_STATUS VARCHAR(3),
    DS_DESCRICAO VARCHAR(100),
    IN_PERMITE_ESCRITA BOOLEAN
);

ALTER TABLE TRA_STATUS_EXAME ADD CONSTRAINT PK_TRA_STATUS_EXAME PRIMARY KEY (CD_STATUS);

---------- GENERATED:

Hibernate: 
    
    create table tvamr_servico_saude (
       id bigint generated by default as identity,
        nm_bairro varchar(255),
        te_cep varchar(255),
        nm_cidade varchar(255),
        nu_cnpj varchar(255),
        nm_estado varchar(255),
        nu_latitude bigint,
        nm_logradouro varchar(255),
        nu_longitude bigint,
        nu_numero_lote bigint,
        nm_completo varchar(255),
        nm_curto varchar(255),
        primary key (id)
    )
    
Hibernate: 
    
    alter table tvamr_exame 
       add constraint FK4bg7b7omwxi6tvcfohovul3u7 
       foreign key (id_servico_saude) 
       references tvamr_servico_saude
Hibernate: 
    
    alter table tvamr_exame 
       add constraint FKttk7swr31m434u6r7vj5jkt2 
       foreign key (cd_status) 
       references tvamr_status_exame