server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    hostname: svc-app-exame
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://svc-eureka-server/eureka