server:
  port: 8080

spring:
  application:
    name: app-exame
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/radb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka