spring:
  application:
    name: gateway-server
  cloud:
    gateway:      routes:      - id: app-exame
        uri: http://localhost:8080/
        predicates:          - Path=/exame/**
      - id: app-usuario
        uri: http://localhost:8081/
        predicates:          - Path=/usuario/**

server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
