apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-exame-deployment
spec:
  template:
    metadata:
      name: app-exame
      labels:
        app: app-exame
    spec:
      containers:
        - name: app-exame
          image: martinsgms/ra-app-exame:v0.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
  selector:
    matchLabels:
      app: app-exame
