apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-usuario-deployment
spec:
  template:
    metadata:
      name: app-usuario
      labels:
        app: app-usuario
    spec:
      containers:
        - name: ra-app-usuario
          image: martinsgms/ra-app-usuario:v0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
  selector:
    matchLabels:
      app: app-usuario

---

apiVersion: v1
kind: Service
metadata:
  name: svc-app-usuario
spec:
  type: ClusterIP
  selector:
    app: app-usuario
  ports:
  - port: 80
    targetPort: 8081
