apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: martinsgms/ra-config-server:v0.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8888
  selector:
    matchLabels:
      app: config-server

---

apiVersion: v1
kind: Service
metadata:
  name: svc-config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - port: 80
    targetPort: 8888