apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  template:
    metadata:
      name: eureka-server
      labels:
        app: eureka-server
    spec:
      containers:
        - name: ra-eureka-server
          image: martinsgms/ra-eureka-server:v0.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8761
  selector:
    matchLabels:
      app: eureka-server

---

apiVersion: v1
kind: Service
metadata:
  name: svc-eureka-server
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
  - port: 80
    targetPort: 8761