apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: martinsgms/ra-eureka-server:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-server-configmap
                key: eureka_service_address