apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
spec:
  template:
    metadata:
      name: gateway-server
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: martinsgms/ra-gateway-server:v0.2
          imagePullPolicy: Always
          ports:
          - containerPort: 5555
  selector:
    matchLabels:
      app: gateway-server

---

apiVersion: v1
kind: Service
metadata:
  name: svc-gateway-server
spec:
  type: LoadBalancer
  selector:
    app: gateway-server
  ports:
  - port: 80
    targetPort: 5555